apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-default-worker-deployment
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
  labels:
    app: celery-default-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-default-worker
  template:
    metadata:
      labels:
        app: celery-default-worker
    spec:
      containers:
      - name: celery-default-worker
        image: {{.Values.deployment.celeryDefaultWorker.image}}:{{.Values.deployment.celeryDefaultWorker.version}}
        {{if .Values.deployment.celeryDefaultWorker.command}}
        command: {{.Values.deployment.celeryDefaultWorker.command }}
        {{end}}
        imagePullPolicy: {{.Values.imagePullPolicy | quote}}
