apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1 
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: {{.Values.deployment.flask.image }}:{{.Values.deployment.flask.version }}
        imagePullPolicy: {{.Values.imagePullPolicy | quote}} 
        ports:
        - containerPort: 5000
