apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
spec:
  selector:
    app: laravel
  type: NodePort
  ports:
    - nodePort: 30000
      port: 8000
      targetPort: 8000
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: 1 
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        
      - name: laravel
        image: {{.Values.deployment.laravel.image}}:{{.Values.deployment.laravel.version}}
        imagePullPolicy: {{.Values.imagePullPolicy | quote}}
        ports:
        - containerPort: 80
