apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
  labels:
    type: local
spec:
  
  {{- with .Values.deployment.redis.PersistentVolume}}
  {{if .storageClassName}}
  # takes default storage class if not specifed, Make Sure you select default storage class
  storageClassName: {{.storageClassName}}
  {{end}}
  capacity:
    storage: {{.storage}}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{.path}}
  {{- end }}
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
spec:
  
  {{- with .Values.deployment.redis.PersistentVolumeClaim}}
  {{if .storageClassName}}
  # takes default storage class if not specifed, Make Sure you select default storage class
  storageClassName: {{.storageClassName}}
  {{end}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.storage}}
  {{- end}}
  
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: {{.Values.namespace | default "atronas-app" | quote }}
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1 
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{.Values.deployment.redis.image}}:{{.Values.deployment.redis.version}}
        imagePullPolicy: {{.Values.imagePullPolicy | quote}} 
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
